import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TodoList from '@/components/TodoList'
import Form from '@/components/form/Form'
import Filter from '@/components/filter/Filter'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>React + Next.js + Redux Todos </h2>
        <Form />
        <Filter />
        <TodoList />
      </main>
    </>
  )
}
